name: Update Commit Time and HTML Files

on:
  push:
    branches:
      - main

jobs:
  update-commit-time-and-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update chz.html
        run: |
          sed -i 's/chz.html/Cheezburger QA Automation Results/g' chz.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add chz.html
          git commit -m "Update chz.html [skip ci]"
          git push
          continue-on-error: true


      - name: Update ebw.html
        run: |
          sed -i 's/ebw.html/EBW QA Automation Results/g' ebw.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ebw.html
          git commit -m "Update ebw.html [skip ci]"
          git push
          continue-on-error: true

      - name: Update Commit Time
        run: |
          current_content=$(cat index.html)
          current_date=$(date +'%m-%d-%Y %H:%M:%S')
          new_content="<div class=\"centered-text\">\n    <h1>🤖 QA Automation</h1>\n</div>\n<p id=\"date\">Test Results Date: $current_date</p>"
          updated_content="${current_content/<div class=\"centered-text\">\n    <h1>🤖 QA Automation<\/h1>\n<\/div>/$new_content}"
          echo -e "$updated_content" > index.html
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update last commit date [skip ci]"
          git push
          continue-on-error: true


