name: Update ebw.html

on:
  push:
    branches:
      - main

jobs:
  update-ebw-html:
    runs-on: ubuntu-latest
    needs: update-chz-html

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update ebw.html
        run: |
          sed -i 's/ebw.html/EBW QA Automation Results/g' ebw.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ebw.html
          git commit -m "Update ebw.html [skip ci]"
          git push
        continue-on-error: true